version: '3.8'

services:
  nginx:
    image: teddysun/shadowsocks-r
    container_name: ssr
    ports:
      - 80:80/tcp
      - 80:80/udp
    restart: always
    volumes:
      - ./data/shadowsocks-r:/etc/shadowsocks-r
