version: '3.8'

services:
  nginx:
    image: teddysun/shadowsocks-r
    container_name: ssr
    ports:
      - 9000:9000
      - 9000:9000/udp
    restart: always
    volumes:
      - ./data/shadowsocks-r:/etc/shadowsocks-r